package com.monyrama.activity;

public enum ExtraNames {
	WELCOME_START, SELECTED_SERVER, SELECTED_EXPENSE, SELECTED_ITEM, SELECTED_ACCOUNT, SELECTED_EXPENSE_PLAN,
	SELECTED_INCOME_SOURCE, SELECTED_INCOME
}
